<?
include("../admin/includes/inc_header.php");
include("../admin/includes/constantes.php");
include("../admin/includes/funciones.php");
include("../admin/includes/fc_global.php");
include("../admin/clases/cls_emp_socio.php");
include("../admin/clases/cls_emp_cupon.php");
include("../admin/clases/cls_emp_usuarios_promociones.php");
include("../admin/clases/cls_emp_cuponsel.php");
include("../admin/clases/charts.class.php");
?>